# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- powershell: |
   $web ="some-web"
   $app ="some-app"
   Write-Host "##vso[task.setvariable variable=MyWebEnv;]$web"
   Write-Host "##vso[task.setvariable variable=MyAppEnv;]$app"
  displayName: 'Output Variables'

- powershell: |
   Write-Host "Set Web to $(MyWebEnv)"
   Write-Host "Set App to $(MyAppEnv)" 
  displayName: 'Output Variables Print'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
